apiVersion: apps/v1
kind: Deployment
metadata:
  name: visaas-prod-report-service
  labels:
    app: visaas-prod-report-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: visaas-prod-report-service
  minReadySeconds: 100
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: visaas-prod-report-service
    spec:
      containers:
        - name: visaas-prod-report-service
          image: 759971283879.dkr.ecr.ap-south-1.amazonaws.com/reports-service:1.0.0-6
          ports:
            - containerPort: 8080
          env:
          - name: DB_CONFIG
            valueFrom:
              secretKeyRef:
                name: db-config-secret
                key: DB_CONFIG
          resources:
            requests:
              cpu: "100m"
              memory: "712Mi"
            limits:
              cpu: "500m"
              memory: "1024Mi"
          volumeMounts:
            - name: efs-storage
              mountPath: /app/logs/
      volumes:
        - name: efs-storage
          persistentVolumeClaim:
            claimName: efs-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: visaas-prod-report-service
spec:
  selector:
    app: visaas-prod-report-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: visaas-prod-report-service-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: visaas-prod-report-service
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 75
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
        - type: Pods
          value: 2
          periodSeconds: 60
        - type: Percent
          value: 50
          periodSeconds: 60
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
        - type: Pods
          value: 1
          periodSeconds: 300
        - type: Percent
          value: 20
          periodSeconds: 300
