apiVersion: apps/v1
kind: Deployment
metadata:
  name: visaas-prod-cancel-nodejs
  labels:
    app: visaas-prod-cancel-nodejs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: visaas-prod-cancel-nodejs
  minReadySeconds: 60
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 5
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: visaas-prod-cancel-nodejs
    spec:
      imagePullSecrets:
        - name: dockerhub-secret  # 🔐 Added secret for pulling image
      containers:
        - name: visaas-prod-cancel-nodejs
          image: 759971283879.dkr.ecr.ap-south-1.amazonaws.com/cancel-nodejs:latest
          ports:
            - containerPort: 3000
          env:
            - name: runfile
              value: "cancel.server.mjs"
          resources:
            requests:
              cpu: "100m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "1024Mi"
          volumeMounts:
            - name: efs-storage
              mountPath: /opt/app/logs/
      volumes:
        - name: efs-storage
          persistentVolumeClaim:
            claimName: efs-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: visaas-prod-cancel-nodejs
spec:
  selector:
    app: visaas-prod-cancel-nodejs
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: visaas-prod-cancel-nodejs-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: visaas-prod-cancel-nodejs
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 75
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
        - type: Pods
          value: 2
          periodSeconds: 60
        - type: Percent
          value: 50
          periodSeconds: 60
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
        - type: Pods
          value: 1
          periodSeconds: 300
        - type: Percent
          value: 20
          periodSeconds: 300
