apiVersion: apps/v1
kind: Deployment
metadata:
  name: visaas-azp-service
  labels:
    app: visaas-azp-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: visaas-azp-service
  minReadySeconds: 100
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 5
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: visaas-azp-service
    spec:
      imagePullSecrets:
        - name: dockerhub-secret   # 🔐 Add secret here
      containers:
        - name: visaas-azp-service
          image: 759971283879.dkr.ecr.ap-south-1.amazonaws.com/convergent-azp:1.0.0-43
          ports:
            - containerPort: 8080
          env:
            - name: DB_CONFIG
              valueFrom:
                secretKeyRef:
                  name: azp-db-config
                  key: DB_CONFIG
          resources:
            requests:
              cpu: "100m"
              memory: "1524Mi"
            limits:
              cpu: "500m"
              memory: "2024Mi"
          volumeMounts:
            - name: efs-storage
              mountPath: /opt/app/logs
      volumes:
        - name: efs-storage
          persistentVolumeClaim:
            claimName: efs-pvc


---

apiVersion: v1
kind: Service
metadata:
  name: visaas-azp-service
spec:
  selector:
    app: visaas-azp-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP

---

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: visaas-azp-service-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: visaas-azp-service
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 75
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
        - type: Pods
          value: 2
          periodSeconds: 60
        - type: Percent
          value: 50
          periodSeconds: 60
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
        - type: Pods
          value: 1
          periodSeconds: 300
        - type: Percent
          value: 20
          periodSeconds: 300
