apiVersion: apps/v1
kind: Deployment
metadata:
  name: visaas-prod-admin-service
  labels:
    app: visaas-prod-admin-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: visaas-prod-admin-service
  minReadySeconds: 60
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 5
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: visaas-prod-admin-service
    spec:
      containers:
      - name: visaas-prod-admin-service
        image: 759971283879.dkr.ecr.ap-south-1.amazonaws.com/vizsaas-core:1.0.0-28
        env:
          - name: VAULT_CONFIG
            valueFrom:
              secretKeyRef:
                name: core-aws-config
                key: VAULT_CONFIG
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "500m"
            memory: "1024Mi"
          limits:
            cpu: "1"
            memory: "1500Mi"
        volumeMounts:
        - name: efs-storage
          mountPath: /app/logs/
      volumes:
      - name: efs-storage
        persistentVolumeClaim:
          claimName: efs-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: visaas-prod-admin-service
spec:
  selector:
    app: visaas-prod-admin-service
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  type: ClusterIP
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: visaas-prod-admin-service-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: visaas-prod-admin-service
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 75
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
        - type: Pods
          value: 2
          periodSeconds: 60
        - type: Percent
          value: 50
          periodSeconds: 60
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
        - type: Pods
          value: 1
          periodSeconds: 300
        - type: Percent
          value: 20
          periodSeconds: 300