---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: visaas-fuse-ui
  labels:
    app: visaas-fuse-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: visaas-fuse-ui
  minReadySeconds: 60
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: visaas-fuse-ui
    spec:
      containers:
      - name: visaas-fuse-ui
        image: 759971283879.dkr.ecr.ap-south-1.amazonaws.com/vizsaas-fuse-ui:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "200m"        
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: visaas-fuse-ui
spec:
  selector:
    app: visaas-fuse-ui
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: visaas-fuse-ui-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: visaas-fuse-ui
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 75
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
        - type: Pods
          value: 2
          periodSeconds: 60
        - type: Percent
          value: 50
          periodSeconds: 60
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
        - type: Pods
          value: 1
          periodSeconds: 300
        - type: Percent
          value: 20
          periodSeconds: 300
